### ISSUE TITLE
2a - Create a component to list all products.

### ISSUE THREAD

**Issue by wilsonvetdev** [Orange-Ostriches/graceshopper-project#6]
**Golden/Happy Path**
- When a customer/visitor visits our e-commerce app, 
- the landing page will be shown
- and the customer will be able to go to 'view all products' through a link,
- and all the products will be shown.

**Requirements:**

- Customer should be able to navigate to the 'All Products" page from anywhere in the app. 

**Dependencies:**

Figma Design - https://www.figma.com/file/ypdxB9lGKgdq3W1qjv1Heh/OO-Wireframe?node-id=0%3A1

**Comment by zwardb** [comment]
- Redux store was setup to GET route to store all products in state.
- AllProducts component created to display all products for sale.
- Refactored AllProducts from class component to functional component using react-redux hooks (kept class component in comments for now).
